import turtle
Andy = turtle.Turtle()
Andy.shape("turtle")
Andy.penup()
Andy.goto(0,300)
Andy.pendown()
Andy.fillcolor("Old Lace")
Andy.pensize(5)
Milly = turtle.Turtle()
Milly.shape("turtle")
Milly.color("blue")
Milly.goto(80,100)
Milly.left(90)
Milly.pensize(5)
Billy = turtle.Turtle()
Billy.shape("turtle")
Billy.color("Red")
Billy.penup()
Billy.goto(225,250)
Billy.pendown()
Billy.pensize(7)
Roger = turtle.Turtle()
Roger.shape("turtle")
Roger.color("Red")
Roger.penup()
Roger.goto(-225,250)
Roger.pendown()
Roger.pensize(10)
Andy.shape("turtle")
Milly.shape("turtle")
Billy.shape("turtle")
Roger.shape("turtle")
Andy.speed(900)
Milly.speed(5)
Billy.speed(900)
Roger.speed(900)

def Hair():
    for i in range(20):
        Roger.begin_fill()
        Roger.circle(i*2)
        Roger.right(70)
        Roger.forward(10)
        Roger.end_fill()
def Hair2():
    for i in range(20):
        Billy.begin_fill()
        Billy.circle(i*2)
        Billy.right(70)
        Billy.forward(10)
        Billy.end_fill()

Andy.begin_fill()
Andy.circle(-300)
Andy.end_fill()
Hair()
Hair2()
Milly.circle(50)


turtle.exitonclick()