import turtle
Andy = turtle.Turtle()
Andy.shape("turtle")
Andy.penup()
Andy.goto(0,300)
Andy.pendown()
Andy.fillcolor("Old Lace")
Andy.pensize(5)
Milly = turtle.Turtle()
Milly.shape("turtle")
Milly.color("pink")
Milly.penup()
Milly.goto(300,-300)
Milly.pendown()
Milly.pensize(5)
Billy = turtle.Turtle()
Billy.shape("turtle")
Billy.color("Medium Orchid")
Billy.penup()
Billy.goto(300,300)
Billy.pendown()
Billy.pensize(7)
Roger = turtle.Turtle()
Roger.shape("turtle")
Roger.color("Red")
Roger.penup()
Roger.goto(-225,250)
Roger.pendown()
Roger.pensize(10)
Andy.shape("turtle")
Milly.shape("turtle")
Billy.shape("turtle")
Roger.shape("turtle")
Andy.speed(900)
Milly.speed(900)
Billy.speed(900)
Roger.speed(900)

def Hair():
    for i in range(20):
        Roger.begin_fill()
        Roger.circle(i*2)
        Roger.right(70)
        Roger.forward(10)
        Roger.end_fill()


Andy.begin_fill()
Andy.circle(-300)
Andy.end_fill()
Hair()


turtle.exitonclick()